### ISSUE TITLE
Image Issue

### ISSUE THREAD

**Issue by m1-key** [ShivBhosale/React-Jupyter-Viewer#5]
How can I upload a local image in this? When I am trying to upload an image, it always shows me the alternate text, not the actual image.
Also, I am not able to use the markdown feature like subscript and superscript.

**Comment by ShivBhosale** [comment]
1. Can you provide an example of how you are trying to upload an image?
2. I'm using a third-party markdown-parser; react-markdown [https://github.com/rexxars/react-markdown](https://github.com/rexxars/react-markdown) 
It currently doesnt support super-script or sub-script

**Comment by m1-key** [comment]
> 1. Can you provide an example of how you are trying to upload an image?
> 2. I'm using a third-party markdown-parser; react-markdown https://github.com/rexxars/react-markdown
>    It currently doesnt support super-script or sub-script

**Comment by m1-key** [comment]
@ShivBhosale reply ?

**Comment by ShivBhosale** [comment]
@m1-key Apologies for late response!
I understand your confusion but the URL that you provided doesn't actually point to an image!
It points to a webpage.

Notice the difference:
**wrong url**
https://**github**.com/m1-key/Thug-Life/blob/master/mask.png

**right url**
https://**raw.githubusercontent**.com/m1-key/Thug-Life/master/mask.png

**Wrong way**
```
![alt text](https://github.com/m1-key/Thug-Life/blob/master/mask.png "Logo Title Text 1")
```
![alt text](https://github.com/m1-key/Thug-Life/blob/master/mask.png "Logo Title Text 1")


**Right way**
```
![alt text](https://raw.githubusercontent.com/m1-key/Thug-Life/master/mask.png "Logo Title Text 1")
```
![alt text](https://raw.githubusercontent.com/m1-key/Thug-Life/master/mask.png "Logo Title Text 1")

I am able to render the image with the following code:

```@javascript
<JupViewer
          title="Jupyter as a Blog!"
          subtitle="I've always wanted to publish my jupyter notebooks as blogs. Finally I can."
          coverImg="https://raw.githubusercontent.com/m1-key/Thug-Life/master/mask.png"
          // file={ipynb}
          file="https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/master/notebooks/00.00-Preface.ipynb"
          // file="https://raw.githubusercontent.com/fastai/course-v3/master/nbs/dl1/00_notebook_tutorial.ipynb"
        />
```

**Comment by m1-key** [comment]
@ShivBhosale Thanks a lot. This Jupyviewer is really awesome component.

**Comment by m1-key** [comment]
@ShivBhosale I met with an issue while passing dynamic ipynbs . i.e when user click on button A it loads notebook A, when user click on button B it loads notebook B. But I am unable to do so. 
Here is the screeshot of the code : 
![Screenshot (158)](https://user-images.githubusercontent.com/39923784/87148824-b9877280-c2cc-11ea-8faf-02f2aa42ce14.png)

Here is the output : 
![Screenshot (157)](https://user-images.githubusercontent.com/39923784/87148859-cf953300-c2cc-11ea-8a18-74884a33b09c.png)

**Comment by ShivBhosale** [comment]
@m1-key Hi Mithilesh. I'm sorry but, I'm seeing this just now. I dont get notified of a comment made on an issue that is already closed! Please consider opening a fresh issue else I wont be notified right away.

Currently the component does not support component-refresh on prop update. Let me try to add this feature over the weekend!
